name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  check-server-coding-style:
    name: Server Coding Style
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/epitech/coding-style-checker:latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Check the coding style
        run: |
          check.sh $(pwd)/zappy_server $(pwd)
          cat coding-style-reports.log | while read LINE; do
            TYPE=$(echo $LINE | cut -d ':' -f 3 | tr -d ' ')
            FILE=$(echo $LINE | cut -d ':' -f 1)
            AT=$(echo $LINE | cut -d ':' -f 2)
            ERROR=$(echo $LINE | cut -d ':' -f 4)
            echo "::error file=$FILE,line=$AT,title=$TYPE coding style error::$ERROR"
          done
          if [[ -s coding-style-reports.log ]]; then
              exit 1
          fi

  server-build-and-test:
    runs-on: ubuntu-latest
    container:
      image: epitechcontent/epitest-docker
    needs: [check-server-coding-style]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build server
        run: |
          cd zappy_server
          make

      - name: Check if server binary exists
        run: |
          cd zappy_server
          test -f server || (echo "Server binary not found" && exit 1)

      - name: Run server tests
        run: |
          cd zappy_server
          make tests_run || echo "No tests configured yet"

      - name: Memory leak check with Valgrind
        run: |
          cd zappy_server
          make valgrind
          timeout 10s valgrind --leak-check=full --error-exitcode=1 ./server --help || true

      - name: Clean build
        run: |
          cd zappy_server
          make fclean